# Generated by Django 5.2 on 2025-04-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blog_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
    ]
